### ISSUE TITLE
Error:   Some peptides in the search file do not have a pair in the peptide list.

### ISSUE THREAD

**Issue by wsnoble** [freejstone/Percolator-RESET#2]
This command worked previously but now issues an error, which seems to indicate that it's having trouble parsing the peptide modifications.

```
CPU: Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17 
2023-11-10 10:22:38.017889 
Command used: /net/noble/vol1/home/noble/proj/freestone/Percolator-RESET/functions/do_FDR_percolator.py --seed 1 --FDR_threshold 1 --overwrite T --narrow T --get_psms T --output_dir 03022016_Clara_MP_Fraction_02 --file_root reset 03022016_Clara_MP_Fraction_02/tide-search.pin Solanum-lycopersicum/tide-index/tide-index.peptides.txt
Successfully read in arguments. 
Using seed: 1. 
Reading in search file. 
Reading in peptide list. 
Taking top 1 PSMs. 
Doing peptide-stem level competition. 
Some peptides in the search file do not have a pair in the peptide list. E.g. V[43 
```
[tide-search.pin.txt](https://github.com/freejstone/Percolator-RESET/files/13322300/tide-search.pin.txt)

I will send the pairs file via slack.

**Comment by wsnoble** [comment]
Follow up to this: the command also fails if you switch to FDR_threshold 0.01 (which is how I ran it previously), so this bug was definitely introduced in the last few revisions.

**Comment by freejstone** [comment]
Yes you are completely right, It was something that I did during our last back and forths. Fix now, thanks!
