### ISSUE TITLE
The least populated class in y has only 2 members, which is less than n_splits=3.

### ISSUE THREAD

**Issue by wsnoble** [freejstone/Percolator-RESET#6]
I am running on a large PIN file, but I'm getting this error message:

```
/net/noble/vol1/home/noble/miniconda3/envs/denovofdr/lib/python3.10/site-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
```

Do I need to worry about this?

The log file and input PIN are attached.

[denovo_fdr.reset.log.txt](https://github.com/freejstone/Percolator-RESET/files/14157612/denovo_fdr.reset.log.txt)
[denovo_fdr.pin.gz](https://github.com/freejstone/Percolator-RESET/files/14157616/denovo_fdr.pin.gz)

**Comment by freejstone** [comment]
Hi Bill, there is a really small positive set for training the SVM (only two). This happens because SVM uses TDC to define a positive set in the direction of Xcorr. The default FDR threshold for this training purpose is `train_FDR_threshold = 0.01`. If it fails to determine a positive set, it will drop the "+1" penalty and try again. In this case, it takes the two highest xcorr scoring PSMs. Because xcorr is not very discriminatory in the denovo setting, this might happen and I would suggest maybe bumping up `train_FDR_threshold` to be much larger. Using your seed, I had to go to at least `train_FDR_threshold = 0.11` before it obtained a non trivial positive set.

Let me know if this doesn't make sense or if you have further questions!

**Comment by wsnoble** [comment]
It seems to me like this should be a fatal error rather than just a warning.  If you only have two positive examples and want to do three splits, it won't work.

**Comment by wsnoble** [comment]
An alternative is to use the glsearch column as the initial dir.  If I do that, then I get a different error:

```
Conducting iterative SVM.
iteration: 0.
/net/noble/vol1/home/noble/miniconda3/envs/denovofdr/lib/python3.10/site-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(
/net/noble/vol1/home/noble/miniconda3/envs/denovofdr/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: 
6 fits failed out of a total of 18.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

```

Again, it seems like perhaps FitFailed should be a fatal error rather than a warning.

**Comment by freejstone** [comment]
Sure I can fitting errors as a fatal error.

**Comment by freejstone** [comment]
I have updated it so that it should trigger an error now:

```
Version: 0+untagged.147.g647bc7e 
CPU: macOS-10.16-x86_64-i386-64bit 
2024-02-08 10:45:41.196849 
Command used: /Volumes/One Touch/Percolator_fix_paper/percolator_with_FDR_control/percolator_RESET/__main__.py --seed 7718 --dynamic_competition F --pair F --get_all_psms T --mult 2 --FDR_threshold 1 --overwrite T --report_decoys T --output_dir 2022_01_13_HAB_timeseries_DDA_39_18-17 --file_root denovo_fdr.reset --remove charge,ExpMass,CalcMass denovo_fdr.pin
Successfully read in arguments. 
Using seed: 7718. 
Reading in search file(s). 
Skipping dynamic level competition (and assuming competition has already been performed). 
Dropping the features from training: charge, ExpMass, CalcMass. 
No initial positive set: removing the +1 penalty.
Conducting iterative SVM.
iteration: 0.
ERROR: The following error occured during SVM training: The least populated class in y has only 2 members, which is less than n_splits=3.
```

**Comment by freejstone** [comment]
This looks like it's resolved, so I will close now.
