### ISSUE TITLE
document how to run the program

### ISSUE THREAD

**Issue by wsnoble** [freejstone/Percolator-RESET#7]
I've been using the old version of PercolatorRESET in which I did `python3 <path_to_project>/functions/do_FDR_percolator.py`.  This file no longer exists.  Can you please update the README file to explain how to actually run PercolatorRESET?

**Comment by freejstone** [comment]
I have a wiki page which has information on:
* parameters: https://github.com/freejstone/Percolator-RESET/wiki/Parameters
* log file: https://github.com/freejstone/Percolator-RESET/wiki/Interpreting-the-log-file
* how to use with examples: https://github.com/freejstone/Percolator-RESET/wiki/How-to-use
* output filess: https://github.com/freejstone/Percolator-RESET/wiki/Explanation-of-output-files

**Comment by wsnoble** [comment]
OK, I think it would be good to add a pointer to this wiki in your README file.

**Comment by freejstone** [comment]
Ok this has been added, closing now.
